"""Per-make metadata: USA homepage URL + a deterministic placeholder
logo color/initials. Logos served from MEDIA_ROOT are generated by
``generate_logos.py``; we deliberately ship plain initials-on-color
SVGs rather than real brand marks (those are trademarked).
"""
from __future__ import annotations

import re

# USA homepages — public facts. Keys are normalized via ``norm_key`` so
# casing/spelling drift in the listings table doesn't matter.
HOMEPAGES: dict[str, str] = {
    "acura": "https://www.acura.com",
    "alfa romeo": "https://www.alfaromeousa.com",
    "aston martin": "https://www.astonmartin.com/en-us",
    "audi": "https://www.audiusa.com",
    "bentley": "https://www.bentleymotors.com/en/usa.html",
    "bmw": "https://www.bmwusa.com",
    "buick": "https://www.buick.com",
    "cadillac": "https://www.cadillac.com",
    "chevrolet": "https://www.chevrolet.com",
    "chrysler": "https://www.chrysler.com",
    "dodge": "https://www.dodge.com",
    "ferrari": "https://www.ferrari.com/en-US",
    "fiat": "https://www.fiatusa.com",
    "ford": "https://www.ford.com",
    "genesis": "https://www.genesis.com",
    "gmc": "https://www.gmc.com",
    "honda": "https://automobiles.honda.com",
    "hyundai": "https://www.hyundaiusa.com",
    "infiniti": "https://www.infinitiusa.com",
    "jaguar": "https://www.jaguarusa.com",
    "jeep": "https://www.jeep.com",
    "karma": "https://www.karmaautomotive.com",
    "kia": "https://www.kia.com/us/en",
    "lamborghini": "https://www.lamborghini.com/en-en",
    "land rover": "https://www.landroverusa.com",
    "lexus": "https://www.lexus.com",
    "lincoln": "https://www.lincoln.com",
    "lotus": "https://www.lotuscars.com/en-US",
    "maserati": "https://www.maserati.com/us/en",
    "mazda": "https://www.mazdausa.com",
    "mclaren": "https://cars.mclaren.com/us-en",
    "mercedes-benz": "https://www.mbusa.com",
    "mini": "https://www.miniusa.com",
    "mitsubishi": "https://www.mitsubishicars.com",
    "nissan": "https://www.nissanusa.com",
    "polestar": "https://www.polestar.com/us",
    "porsche": "https://www.porsche.com/usa",
    "ram": "https://www.ramtrucks.com",
    "rolls royce": "https://www.rolls-roycemotorcars.com/en_US.html",
    "rolls-royce": "https://www.rolls-roycemotorcars.com/en_US.html",
    "saab": "https://en.wikipedia.org/wiki/Saab_Automobile",
    "subaru": "https://www.subaru.com",
    "tesla": "https://www.tesla.com",
    "toyota": "https://www.toyota.com",
    "volkswagen": "https://www.vw.com",
    "volvo": "https://www.volvocars.com/us",
}

# Brand-adjacent accent colors for the placeholder background. These are
# common color associations (Ford = blue, Ferrari = red, etc.) but the
# logos themselves are just initials on the chosen color — not the
# protected wordmarks.
COLORS: dict[str, str] = {
    "acura": "#1d1d1f",
    "alfa romeo": "#a3001b",
    "aston martin": "#0a4f3c",
    "audi": "#bb0a30",
    "bentley": "#102a18",
    "bmw": "#0066b1",
    "buick": "#aa0000",
    "cadillac": "#2c2c2c",
    "chevrolet": "#c5a572",
    "chrysler": "#1d1d1f",
    "dodge": "#c8102e",
    "ferrari": "#d40000",
    "fiat": "#a51c30",
    "ford": "#003478",
    "genesis": "#1f2937",
    "gmc": "#a91d22",
    "honda": "#cc0000",
    "hyundai": "#002c5f",
    "infiniti": "#1f2937",
    "jaguar": "#1f3a36",
    "jeep": "#374151",
    "karma": "#0e2a3a",
    "kia": "#05141f",
    "lamborghini": "#0c0c0c",
    "land rover": "#005a30",
    "lexus": "#0c0c0c",
    "lincoln": "#1a1a1a",
    "lotus": "#0e6b3f",
    "maserati": "#003a70",
    "mazda": "#101820",
    "mclaren": "#ff8000",
    "mercedes-benz": "#1f2937",
    "mini": "#000000",
    "mitsubishi": "#e60012",
    "nissan": "#c3002f",
    "polestar": "#262626",
    "porsche": "#c8102e",
    "ram": "#1f2937",
    "rolls royce": "#5a2a82",
    "rolls-royce": "#5a2a82",
    "saab": "#0a4f6e",
    "subaru": "#1d3c84",
    "tesla": "#cc0000",
    "toyota": "#eb0a1e",
    "volkswagen": "#001e50",
    "volvo": "#003057",
}

DEFAULT_COLOR = "#3699ff"


def norm_key(make: str) -> str:
    return (make or "").strip().lower()


def slug_for_filename(make: str) -> str:
    """Filesystem-safe slug — used as the SVG filename."""
    raw = (make or "").lower()
    raw = re.sub(r"[^a-z0-9]+", "-", raw).strip("-")
    return raw or "unknown"


def initials_for(make: str) -> str:
    parts = re.split(r"[\s\-_]+", (make or "").strip())
    parts = [p for p in parts if p]
    if not parts:
        return "?"
    if len(parts) == 1:
        word = parts[0]
        return word[:3].upper() if len(word) <= 4 else word[:2].upper()
    return (parts[0][0] + parts[1][0]).upper()


def homepage_for(make: str) -> str | None:
    return HOMEPAGES.get(norm_key(make))


def color_for(make: str) -> str:
    return COLORS.get(norm_key(make), DEFAULT_COLOR)


def logo_url_for(make: str) -> str:
    return f"/media/logos/{slug_for_filename(make)}.svg"
