# Generated by Django 5.0 on 2026-05-14 15:20

import accounts.models
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Primary identifier; used to log in.', max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(blank=True, help_text='How the user wants to be addressed.', max_length=200, verbose_name='full name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='E.164 format (e.g. +14155551234). Optional at signup; required before phone-gated actions.', max_length=128, null=True, region=None, unique=True, verbose_name='phone number')),
                ('is_email_verified', models.BooleanField(default=False, help_text="Set by the email-confirmation flow (allauth) or by an OAuth provider's verified-email claim.", verbose_name='email verified')),
                ('is_phone_verified', models.BooleanField(default=False, help_text='Set when the user completes phone OTP verification.', verbose_name='phone verified')),
                ('marketing_opt_in', models.BooleanField(default=False, help_text='Did the user opt in to product + dealer-promo emails at signup?', verbose_name='marketing emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
