# Generated by Django 5.0 on 2026-05-14 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOTPChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('code_hash', models.CharField(max_length=64)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('log', 'Log (dev only)')], default='email', max_length=16)),
                ('destination_hint', models.CharField(blank=True, help_text='Masked destination shown to the user, e.g. j••@gmail.com or +1•••6526.', max_length=200)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_otp_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_ad_user_id_2137bd_idx')],
            },
        ),
    ]
